spring:
 application:
  name: eureka-server
 profiles:
    active:
    - dev

server:
 port: 8761

management:
 endpoints:
  web: 
   exposure:
    include: "*"



eureka: 
 client:
  registerWithEureka: false
  fetchRegistry: false

